### PR TITLE
fix: `fsHelper.pathExist` when path does not exist

### LINKED ISSUE #481: Deleting one file from LWC bundle puts entire component to destructiveChanges
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

Deleting only one of the files in the LWC bundle (for example css file) leads to entire component being added to the destructiveChanges.xml

### What is the parameter and the value you used with it?

```
sfdx sgd:source:delta --to HEAD --from HEAD~1 --source="force-app/" --generate-delta --output __diff/ --ignore .forceignore
```

### What is the expected result?

LWC component is added to the package.xml and diff sources folder.

### What is the actual result?

LWC is added to the destructiveChanges.xml

## Steps to reproduce

- Clone the playground: https://github.com/nikitakarpenkov/sfdx-git-delta-reproduction-playground
- Run `sfdx sgd:source:delta -d -f HEAD~1`

## Execution context

---

**Operating System:** Ubuntu 22.04 and Mac OS Monterey 12.3

**yarn version:** 1.22.19

**node version:** 16.17.1

**git version:** 2.39.2

**sfdx version:** 7.188.1

**sgd plugin version:** 5.13.2

## More information (optional)

---

```bash
$ git diff --name-status --no-renames HEAD~1 HEAD
```

```
D       sgd/reproduction/playground/lwc/testComponent/testComponent.css
```

### PR DESCRIPTION
**Pull request by nikitakarpenkov**
## Explain your changes

Corrects a bug where an existing path in git was identified as non-existent.

## Does this close any currently open issues?

---

closes #481

- [ ] Jest test added to check the fix is applied.

## Any particular element that can be tested locally

---

## Any other comments

---

### CODE REVIEW

**Comment by scolladon** [comment]
Hi @nikitakarpenkov !

Thank you very much for this PR, really appreciated

I'll check the issue locally soon and the fix as well.

What would be great is to add a unit test in the related test class so we can make sure the failing use case is covered

File: src/utils/fsHelper.js [hunk 1]
```diff
@@ -63,7 +63,7 @@ const readPathFromGit = async (path, config) => {
 
 const pathExists = async (path, config) => {
   const data = await readPathFromGit(path, config)
-  return data.startsWith(FATAL)
+  return !!data && !data.startsWith(FATAL)
```
Comment (scolladon) [inline src/utils/fsHelper.js:66]: **suggestion:** I think an [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) would work here

```suggestion
  return !data?.startsWith(FATAL)
```

**Review by scolladon — APPROVED** [review]
LGTM
